services:
  nordvpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nordvpn
    restart: unless-stopped
    ports:
      - "1080:1080" #socks proxy port
      - "8888:8888" #http proxy port
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # disable ipv6
    privileged: true # required >= 3.17.0
    cap_add:
      - NET_ADMIN               # Required
    environment:
      - TZ=Europe/Madrid
      - #- NORDVPN_VERSION=3.16.9 #install required version of nordvpn's client. Downgrade allowed.
      - GROUP=P2P #default P2P, Africa_The_Middle_East_And_India, Asia_Pacific, Europe, Onion_Over_VPN, P2P, Standard_VPN_Servers, The_Americas
      - ANALYTICS=off # or on, sending anonymous aggregate data: crash reports, OS version, marketing performance, and feature usage data
        #- CONNECT= #Optionnal, override COUNTRY, specify country+serveur number like uk715
      - COUNTRY=ch # optional, default argentina.
        KILLERSWITCH=on #Optional, on by default, kill Switch is a feature helping you prevent unprotected access to the internet when your traffic doesn't go through a NordVPN server.
        #- CYBER_SEC=off #CyberSec is a feature protecting you from ads, unsafe connections, and malicious sites
      - TECHNOLOGY=NordLynx #openvpn or nordlynx (default)
      - DANTE_ERRORLOG=/dev/stdout #Optional, /dev/null by default
      #- DANTE_DEBUG=0 # Optional, 0-9
    secrets:
      - NORDVPN_CREDS
      - TINY_CREDS

secrets:
  NORDVPN_CREDS:
    file: ./nordvpn_creds
  TINYCREDS:
    file: ./tiny_creds
